[package]
name = "a_bc"
description = "make simple lexers"
authors = ["mnmun <mnmnmun@proton.me>"]
version = "0.0.0"
homepage = "https://github.com/mnmun/a_bc"
repository = "https://github.com/mnmun/a_bc"
readme = "README.md"
license = "MIT"
edition = "2024"

[dev-dependencies]
pretty_assertions = "1.4.1"
criterion = { version = "0.5", features = [ "html_reports" ] }
tokio = { version = "1.53.1", features = [ "rt", "rt-multi-thread", "macros", "time" ] }

[dependencies]
getset = "0.1.6"
memchr = "2"


