[package]
name = "json"
description = "simplest json lexer"
version = "0.0.0"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
license.workspace = true
edition.workspace = true

[lib]
path = "lib.rs"

[[bench]]
name = "json"
harness = false

[dev-dependencies]
pretty_assertions.workspace = true
criterion.workspace = true
tokio.workspace = true

[dependencies]
a_bc.workspace = true

memchr.workspace = true
